services:
  web:
    image: ${DOCKER_IMAGE_WEB}:wp${DOCKER_IMAGE_WP_VERSION}-php${DOCKER_IMAGE_PHP_VERSION}
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./wp-config/php-config.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./www:/var/www/html
      - ./plugins:/var/plugins
    ports:
      - "80:80"
  db:
    image: mariadb
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./wp-config/phpmyadmin.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    ports:
        - "8080:80"
    links:
        - db:db
  mailhog:
      image: mailhog/mailhog
      ports:
        - "1025:1025"
        - "8025:8025"